# Generated by Django 5.2.6 on 2025-12-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_stage',
            field=models.CharField(default='symptom_intake', max_length=50),
        ),
    ]
