// medicalMap.ts
export const medicalMap: Record<string, string> = {
  // === FEVER SYMPTOMS ===
  // Common misspellings
  "fevr": "fever",
  "feveeer": "fever",
  "feverr": "fever",
  "feaver": "fever",
  "feverish": "fever",
  "high temp": "fever",
  "high temperature": "fever",
  "elevated temp": "fever",
  "temp high": "fever",
  "temperature high": "fever",
  // Hinglish terms
  "bukhar": "fever",
  "bukhaar": "fever",
  "bukhar hai": "fever",
  "bukhar aa raha hai": "fever",
  "bukhar aa raha": "fever",
  "bukhar aa gaya": "fever",
  "bukhar aa gaya hai": "fever",
  "bukhar hai mujhe": "fever",
  "mujhe bukhar hai": "fever",
  "mujhe bukhar aa raha hai": "fever",

  // === COUGH SYMPTOMS ===
  "khasi": "cough",
  "khaasi": "cough",
  "khansi": "cough",
  "khansii": "cough",
  "coughing": "cough",
  "dry cough": "cough",
  "wet cough": "cough",
  "productive cough": "cough",
  "non productive cough": "cough",
  "coughing up": "cough",
  "khasi aa rahi hai": "cough",
  "khasi aa raha hai": "cough",
  "khasi ho rahi hai": "cough",
  "khasi ho raha hai": "cough",
  "mujhe khasi aa rahi hai": "cough",
  "mujhe khasi ho rahi hai": "cough",

  // === HEADACHE SYMPTOMS ===
  "sirdard": "headache",
  "sir dard": "headache",
  "head ache": "headache",
  "headach": "headache",
  "hedache": "headache",
  "headake": "headache",
  "migraine": "headache",
  "headpain": "headache",
  "pain in head": "headache",
  "head hurting": "headache",
  "sir mein dard": "headache",
  "sir mein dard hai": "headache",
  "sir dard hai": "headache",
  "sir dard ho raha hai": "headache",
  "sir mein dard ho raha hai": "headache",
  "mujhe sir dard hai": "headache",
  "mujhe sir mein dard hai": "headache",

  // === STOMACH PAIN SYMPTOMS ===
  "pet dard": "stomach pain",
  "pet mein dard": "stomach pain",
  "stomach ache": "stomach pain",
  "stomach pain": "stomach pain",
  "abdominal pain": "stomach pain",
  "abdomen pain": "stomach pain",
  "belly pain": "stomach pain",
  "belly ache": "stomach pain",
  "tummy pain": "stomach pain",
  "tummy ache": "stomach pain",
  "pet mein jalan": "stomach pain",
  "pet mein dard hai": "stomach pain",
  "pet dard hai": "stomach pain",
  "pet dard ho raha hai": "stomach pain",
  "pet mein dard ho raha hai": "stomach pain",
  "mujhe pet dard hai": "stomach pain",
  "mujhe pet mein dard hai": "stomach pain",

  // === DIZZINESS SYMPTOMS ===
  "chakkar": "dizziness",
  "chakkar aa raha hai": "dizziness",
  "chakkar aa raha": "dizziness",
  "chakkar aa gaya": "dizziness",
  "chakkar aa gaya hai": "dizziness",
  "dizzy": "dizziness",
  "dizzyness": "dizziness",
  "vertigo": "dizziness",
  "lightheaded": "dizziness",
  "light headed": "dizziness",
  "feeling dizzy": "dizziness",
  "chakkar sa aa raha hai": "dizziness",
  "chakkar sa lag raha hai": "dizziness",
  "mujhe chakkar aa raha hai": "dizziness",
  "mujhe chakkar aa gaya hai": "dizziness",

  // === COLD SYMPTOMS ===
  "jukaam": "cold",
  "jukam": "cold",
  "jukham": "cold",
  "sardi": "cold",
  "sardi jukaam": "cold",
  "common cold": "cold",
  "running nose": "cold",
  "runny nose": "cold",
  "stuffy nose": "cold",
  "nasal congestion": "cold",
  "sneezing": "cold",
  "sneeze": "cold",
  "sardi lag gayi": "cold",
  "sardi ho gayi": "cold",
  "jukaam ho gaya": "cold",
  "jukaam aa gaya": "cold",
  "mujhe sardi lag gayi": "cold",
  "mujhe jukaam ho gaya": "cold",

  // === RASH SYMPTOMS ===
  "kharash": "rash",
  "kharish": "rash",
  "khujli": "rash",
  "itching": "rash",
  "itch": "rash",
  "skin rash": "rash",
  "skin irritation": "rash",
  "allergic rash": "rash",
  "red spots": "rash",
  "red patches": "rash",
  "kharash aa gaya": "rash",
  "kharash ho gaya": "rash",
  "khujli ho rahi hai": "rash",
  "khujli aa rahi hai": "rash",
  "mujhe kharash aa gaya": "rash",
  "mujhe khujli ho rahi hai": "rash",

  // === NAUSEA SYMPTOMS ===
  "nausea": "nausea",
  "nauseous": "nausea",
  "feeling sick": "nausea",
  "want to vomit": "nausea",
  "feeling like vomiting": "nausea",
  "ulți aa rahi hai": "nausea",
  "mujhe ulți aa rahi hai": "nausea",
  "mujhe ulti aa rahi hai": "nausea",
  "feeling nauseous": "nausea",
  "sick feeling": "nausea",

  // === VOMITING SYMPTOMS ===
  "vomiting": "vomiting",
  "vomit": "vomiting",
  "throw up": "vomiting",
  "throwing up": "vomiting",
  "ulți": "vomiting",
  "ulti": "vomiting",
  "ulți ho gayi": "vomiting",
  "ulti ho gayi": "vomiting",
  // "ulți aa rahi hai": "vomiting",
  "ulti aa rahi hai": "vomiting",
  "mujhe ulți ho gayi": "vomiting",
  "mujhe ulti ho gayi": "vomiting",

  // === DIARRHEA SYMPTOMS ===
  "diarrhea": "diarrhea",
  "diarrhoea": "diarrhea",
  "loose motion": "diarrhea",
  "loose motions": "diarrhea",
  "loose stools": "diarrhea",
  "watery stools": "diarrhea",
  "frequent bowel movement": "diarrhea",
  "dast": "diarrhea",
  "dasta": "diarrhea",
  "dast aa raha hai": "diarrhea",
  "dasta aa raha hai": "diarrhea",
  "loose motion ho raha hai": "diarrhea",
  "mujhe dast aa raha hai": "diarrhea",

  // === FATIGUE SYMPTOMS ===
  "fatigue": "fatigue",
  "tired": "fatigue",
  "tiredness": "fatigue",
  "exhaustion": "fatigue",
  "weakness": "fatigue",
  "feeling weak": "fatigue",
  "lack of energy": "fatigue",
  "low energy": "fatigue",
  "thakavat": "fatigue",
  "thakan": "fatigue",
  "thak gaya": "fatigue",
  "thak gayi": "fatigue",
  "thakan mahsus ho rahi hai": "fatigue",
  "mujhe thakan mahsus ho rahi hai": "fatigue",

  // === SHORTNESS OF BREATH SYMPTOMS ===
  "shortness of breath": "shortness of breath",
  "breathlessness": "shortness of breath",
  "difficulty breathing": "shortness of breath",
  "breathing difficulty": "shortness of breath",
  "hard to breathe": "shortness of breath",
  "can't breathe": "shortness of breath",
  "sansi rukti hai": "shortness of breath",
  "sansi ruk rahi hai": "shortness of breath",
  "sansi rukti hai mujhe": "shortness of breath",
  "mujhe sansi rukti hai": "shortness of breath",
  "breathing problem": "shortness of breath",

  // === CHEST PAIN SYMPTOMS ===
  "chest pain": "chest pain",
  "chest ache": "chest pain",
  "pain in chest": "chest pain",
  "chest hurting": "chest pain",
  "cardiac pain": "chest pain",
  "heart pain": "chest pain",
  "pain in heart": "chest pain",
  "seene mein dard": "chest pain",
  "seene mein dard hai": "chest pain",
  "seene mein dard ho raha hai": "chest pain",
  "mujhe seene mein dard hai": "chest pain",

  // === BACK PAIN SYMPTOMS ===
  "back pain": "back pain",
  "back ache": "back pain",
  "pain in back": "back pain",
  "back hurting": "back pain",
  "lower back pain": "back pain",
  "upper back pain": "back pain",
  "backpain": "back pain",
  "peeth mein dard": "back pain",
  "peeth mein dard hai": "back pain",
  "peeth dard": "back pain",
  "peeth dard hai": "back pain",
  "mujhe peeth mein dard hai": "back pain",

  // === JOINT PAIN SYMPTOMS ===
  "joint pain": "joint pain",
  "joint ache": "joint pain",
  "pain in joints": "joint pain",
  "joints hurting": "joint pain",
  "arthritis": "joint pain",
  "arthritic pain": "joint pain",
  "gathiya": "joint pain",
  "gathiya dard": "joint pain",
  "gathiya mein dard": "joint pain",
  "gathiya dard hai": "joint pain",
  "mujhe gathiya dard hai": "joint pain",

  // === MUSCLE PAIN SYMPTOMS ===
  "muscle pain": "muscle pain",
  "muscle ache": "muscle pain",
  "pain in muscles": "muscle pain",
  "muscles hurting": "muscle pain",
  "body ache": "muscle pain",
  "body pain": "muscle pain",
  "myalgia": "muscle pain",
  "muscle soreness": "muscle pain",
  "sore muscles": "muscle pain",
  "pair mein dard": "muscle pain",
  "pair dard": "muscle pain",
  "pair mein dard hai": "muscle pain",
  "pair dard hai": "muscle pain",
  "mujhe pair mein dard hai": "muscle pain",

  // === SORE THROAT SYMPTOMS ===
  "sore throat": "sore throat",
  "throat pain": "sore throat",
  "pain in throat": "sore throat",
  "throat hurting": "sore throat",
  "throat irritation": "sore throat",
  "galaa kharab": "sore throat",
  "galaa mein dard": "sore throat",
  "galaa dard": "sore throat",
  "galaa mein dard hai": "sore throat",
  "galaa dard hai": "sore throat",
  "mujhe galaa mein dard hai": "sore throat",

  // === BLOOD PRESSURE ===
  "bp": "blood pressure",
  "high bp": "hypertension",
  "low bp": "hypotension",
  "bp high": "hypertension",
  "bp low": "hypotension",
  "high blood pressure": "hypertension",
  "low blood pressure": "hypotension",
  "hypertension": "hypertension",
  "hypotension": "hypotension",

  // === DIABETES ===
  "sugar": "diabetes",
  "blood sugar": "diabetes",
  "high sugar": "diabetes",
  "sugar high": "diabetes",
  "diabetes": "diabetes",
  "diabetic": "diabetes",

  // === CONSTIPATION ===
  "constipation": "constipation",
  "kabz": "constipation",
  "kabz hai": "constipation",
  "kabz ho gaya": "constipation",
  "kabz aa gaya": "constipation",
  "mujhe kabz hai": "constipation",
  "mujhe kabz ho gaya": "constipation",

  // === URINARY PROBLEMS ===
  "peshab karte waqt jalan": "urinary burning",
  "peshab mein jalan": "urinary burning",
  "burning urination": "urinary burning",
  "painful urination": "urinary burning",
  "urinary frequency": "frequent urination",
  "frequent urination": "frequent urination",
  "frequent peeing": "frequent urination",
  "peshab jyada aa raha hai": "frequent urination",
  "peshab bar bar aa raha hai": "frequent urination",

  // === CHILLS ===
  "chills": "chills",
  "shivering": "chills",
  "feeling cold": "chills",
  "cold sensation": "chills",
  "thand lag rahi hai": "chills",
  "thand mahsus ho rahi hai": "chills",
  "mujhe thand lag rahi hai": "chills",

  // === NIGHT SWEATS ===
  "night sweats": "night sweats",
  "sweating at night": "night sweats",
  "night time sweating": "night sweats",
  "raat ko pasina": "night sweats",
  "raat ko pasina aa raha hai": "night sweats",

  // === WEIGHT CHANGES ===
  "weight loss": "weight loss",
  "weight gain": "weight gain",
  "losing weight": "weight loss",
  "gaining weight": "weight gain",
  "weight decrease": "weight loss",
  "weight increase": "weight gain",

  // === SWELLING ===
  "swelling": "swelling",
  "edema": "swelling",
  "swollen": "swelling",
  "puffiness": "swelling",
  "soojan": "swelling",
  "soojan aa gaya": "swelling",
  "soojan ho gaya": "swelling",
  "mujhe soojan aa gaya": "swelling",

  // === PALPITATIONS ===
  "palpitations": "palpitations",
  "heart racing": "palpitations",
  "fast heartbeat": "palpitations",
  "heart pounding": "palpitations",
  "dil ki dharkan tez": "palpitations",
  "dil tez dhark raha hai": "palpitations",
  "mujhe dil tez dhark raha hai": "palpitations",

  // === ANXIETY ===
  "anxiety": "anxiety",
  "anxious": "anxiety",
  "feeling anxious": "anxiety",
  "nervousness": "anxiety",
  "tension": "anxiety",
  "stress": "anxiety",
  "bekarari": "anxiety",
  "bekarari mahsus ho rahi hai": "anxiety",

  // === DEPRESSION ===
  "depression": "depression",
  "depressed": "depression",
  "feeling depressed": "depression",
  "sadness": "depression",
  "low mood": "depression",
  "udasi": "depression",
  "udasi mahsus ho rahi hai": "depression",

  // === INSOMNIA ===
  "insomnia": "insomnia",
  "can't sleep": "insomnia",
  "difficulty sleeping": "insomnia",
  "sleep problems": "insomnia",
  "sleeplessness": "insomnia",
  "neend nahi aa rahi": "insomnia",
  "neend nahi aa raha hai": "insomnia",
  "mujhe neend nahi aa rahi": "insomnia",

  // === BLURRED VISION ===
  "blurred vision": "blurred vision",
  "blurry vision": "blurred vision",
  "vision problems": "blurred vision",
  "can't see clearly": "blurred vision",
  "ankhon ka dhundhla hona": "blurred vision",
  "ankhein dhundhli ho gayi": "blurred vision",

  // === EAR PAIN ===
  "ear pain": "ear pain",
  "ear ache": "ear pain",
  "pain in ear": "ear pain",
  "ear hurting": "ear pain",
  "kaan mein dard": "ear pain",
  "kaan dard": "ear pain",
  "kaan mein dard hai": "ear pain",

  // === HEARING LOSS ===
  "hearing loss": "hearing loss",
  "can't hear": "hearing loss",
  "hearing problems": "hearing loss",
  "deafness": "hearing loss",
  "sunai nahi deta": "hearing loss",
  "sunai nahi deti": "hearing loss",

  // === TINNITUS ===
  "tinnitus": "tinnitus",
  "ringing in ears": "tinnitus",
  "ear ringing": "tinnitus",
  "noise in ears": "tinnitus",
  "kaan mein awaaz": "tinnitus",
  "kaan mein awaaz aa rahi hai": "tinnitus",

  // === NUMBNESS ===
  "numbness": "numbness",
  "numb": "numbness",
  "tingling": "numbness",
  "pins and needles": "numbness",
  "sensation loss": "numbness",
  "suhaapan": "numbness",
  "suhaapan mahsus ho raha hai": "numbness",

  // === ACID REFLUX ===
  "acid reflux": "acid reflux",
  "heartburn": "acid reflux",
  "acidity": "acid reflux",
  "gas": "acid reflux",
  "indigestion": "acid reflux",
  "teziyat": "acid reflux",
  "teziyat ho rahi hai": "acid reflux",
  "mujhe teziyat ho rahi hai": "acid reflux",

  // === BLOATING ===
  "bloating": "bloating",
  "bloated": "bloating",
  "gas in stomach": "bloating",
  "stomach gas": "bloating",
  "pet mein gas": "bloating",
  "pet mein gas hai": "bloating",

  // === HICCUPS ===
  "hiccups": "hiccups",
  "hiccup": "hiccups",
  "hikava": "hiccups",
  "hikava aa raha hai": "hiccups",
  "hikava aa rahi hai": "hiccups",

  // === EXCESSIVE THIRST ===
  "excessive thirst": "excessive thirst",
  "thirsty": "excessive thirst",
  "increased thirst": "excessive thirst",
  "polyuria": "excessive thirst",
  "pyaas jyada": "excessive thirst",
  "pyaas jyada lag rahi hai": "excessive thirst",

  // === COLD INTOLERANCE ===
  "cold intolerance": "cold intolerance",
  // "feeling cold": "cold intolerance",
  "always cold": "cold intolerance",
  "heat intolerance": "heat intolerance",
  "feeling hot": "heat intolerance",
  "always hot": "heat intolerance",

  // === HAIR LOSS ===
  "hair loss": "hair loss",
  "hair fall": "hair loss",
  "balding": "hair loss",
  "hair thinning": "hair loss",
  "baal gir rahe hain": "hair loss",
  "baal gir rahe hai": "hair loss",

  // === DRY SKIN ===
  "dry skin": "dry skin",
  "skin dryness": "dry skin",
  "oily skin": "oily skin",
  "skin oiliness": "oily skin",
  "acne": "acne",
  "pimples": "acne",
  "skin problems": "acne",

  // === MENSTRUAL PAIN ===
  "menstrual pain": "menstrual pain",
  "period pain": "menstrual pain",
  "painful periods": "menstrual pain",
  "cramps": "menstrual pain",
  "dysmenorrhea": "menstrual pain",
  "mahavaari mein dard": "menstrual pain",
  "mahavaari dard": "menstrual pain",

  // === BREAST PAIN ===
  "breast pain": "breast pain",
  "breast tenderness": "breast pain",
  "breast lump": "breast lump",
  "breast swelling": "breast lump",

  // === INFERTILITY ===
  "infertility": "infertility",
  "can't conceive": "infertility",
  "difficulty conceiving": "infertility",
  "bacche nahi ho rahe": "infertility",

  // === EYE PAIN ===
  "eye pain": "eye pain",
  "eye ache": "eye pain",
  "pain in eyes": "eye pain",
  "eyes hurting": "eye pain",
  "ankhon mein dard": "eye pain",
  "ankhon mein dard hai": "eye pain",

  // === NOSEBLEED ===
  "nosebleed": "nosebleed",
  "nose bleeding": "nosebleed",
  "blood from nose": "nosebleed",
  "nak se khoon": "nosebleed",
  "nak se khoon aa raha hai": "nosebleed",

  // === LOSS OF SMELL/TASTE ===
  "loss of smell": "loss of smell",
  "can't smell": "loss of smell",
  "anosmia": "loss of smell",
  "loss of taste": "loss of taste",
  "can't taste": "loss of taste",
  "ageusia": "loss of taste",
  "smell nahi aa raha": "loss of smell",
  "taste nahi aa raha": "loss of taste",

  // === BLOOD IN URINE/STOOL ===
  "blood in urine": "blood in urine",
  "hematuria": "blood in urine",
  "blood in stool": "blood in stool",
  "bloody stool": "blood in stool",
  "rectal bleeding": "blood in stool",
  "peshab mein khoon": "blood in urine",
  "stool mein khoon": "blood in stool",

  // === SWEATING ===
  "excessive sweating": "excessive sweating",
  "sweating": "excessive sweating",
  "hyperhidrosis": "excessive sweating",
  "pasina jyada": "excessive sweating",
  "pasina aa raha hai": "excessive sweating",

  // === SNEEZING ===
  // "sneezing": "sneezing",
  // "sneeze": "sneezing",
  "continuous sneezing": "sneezing",
  "chhink": "sneezing",
  "chhink aa rahi hai": "sneezing",

  // === RUNNY NOSE ===
  // "runny nose": "runny nose",
  "nasal discharge": "runny nose",
  "nose running": "runny nose",
  "nak se paani": "runny nose",
  "nak se paani aa raha hai": "runny nose",

  // === SORE EYES ===
  "sore eyes": "sore eyes",
  "eye irritation": "sore eyes",
  "red eyes": "sore eyes",
  "conjunctivitis": "sore eyes",
  "ankhein laal": "sore eyes",
  "ankhein laal ho gayi": "sore eyes",

  // === LOSS OF APPETITE ===
  "loss of appetite": "loss of appetite",
  "no appetite": "loss of appetite",
  "not hungry": "loss of appetite",
  "bhukh nahi": "loss of appetite",
  "bhukh nahi lag rahi": "loss of appetite",

  // === THROAT IRRITATION ===
  // "throat irritation": "throat irritation",
  "scratchy throat": "throat irritation",
  "dry throat": "throat irritation",
  "galaa sukha": "throat irritation",
  "galaa sukha ho gaya": "throat irritation",

  // === COUGH WITH PHLEGM ===
  "cough with phlegm": "cough with phlegm",
  "phlegm": "cough with phlegm",
  "mucus": "cough with phlegm",
  "sputum": "cough with phlegm",
  "balgam": "cough with phlegm",
  "balgam aa raha hai": "cough with phlegm",

  // === BODY ACHES ===
  "body aches": "body aches",
  "generalized pain": "body aches",
  "all over pain": "body aches",
  // "body pain": "body aches",
  "pura jism dard": "body aches",
  "pura jism dard kar raha hai": "body aches",

  // === WEAKNESS ===
  // "weakness": "weakness",
  "general weakness": "weakness",
  "body weakness": "weakness",
  "kamzori": "weakness",
  "kamzori mahsus ho rahi hai": "weakness",

  // === IRRITABILITY ===
  "irritability": "irritability",
  "irritable": "irritability",
  "easily irritated": "irritability",
  "mood swings": "irritability",
  "chidchidapan": "irritability",
  "chidchidapan aa rahi hai": "irritability",

  // === CONFUSION ===
  "confusion": "confusion",
  "confused": "confusion",
  "mental confusion": "confusion",
  "bewildered": "confusion",
  "pareshani": "confusion",
  "pareshani ho rahi hai": "confusion",

  // === MEMORY PROBLEMS ===
  "memory problems": "memory problems",
  "forgetfulness": "memory problems",
  "can't remember": "memory problems",
  "memory loss": "memory problems",
  "yaad nahi aa raha": "memory problems",

  // === DIFFICULTY SWALLOWING ===
  "difficulty swallowing": "difficulty swallowing",
  "swallowing problems": "difficulty swallowing",
  "dysphagia": "difficulty swallowing",
  "nigalne mein dikkat": "difficulty swallowing",

  // === FREQUENT HEADACHES ===
  "frequent headaches": "frequent headaches",
  "recurring headaches": "frequent headaches",
  "chronic headaches": "frequent headaches",
  "regular headaches": "frequent headaches",

  // === MUSCLE CRAMPS ===
  "muscle cramps": "muscle cramps",
  // "cramps": "muscle cramps",
  "muscle spasms": "muscle cramps",
  "charlie horse": "muscle cramps",
  "pair mein khinchav": "muscle cramps",

  // === SKIN IRRITATION ===
  // "skin irritation": "skin irritation",
  // "skin rash": "skin irritation",
  "dermatitis": "skin irritation",
  "eczema": "skin irritation",
  // "khujli": "skin irritation",

  // === BREATHING DIFFICULTY ===
  // "breathing difficulty": "breathing difficulty",
  "respiratory distress": "breathing difficulty",
  "labored breathing": "breathing difficulty",
  "sansi mein dikkat": "breathing difficulty",

  // === CHEST TIGHTNESS ===
  "chest tightness": "chest tightness",
  "tight chest": "chest tightness",
  "chest constriction": "chest tightness",
  "seene mein jhak": "chest tightness",

  // === HEART PALPITATIONS ===
  "heart palpitations": "heart palpitations",
  "irregular heartbeat": "heart palpitations",
  "arrhythmia": "heart palpitations",
  "dil ki dharkan irregular": "heart palpitations",

  // === FATIGUE ===
  "chronic fatigue": "chronic fatigue",
  "extreme tiredness": "chronic fatigue",
  "persistent fatigue": "chronic fatigue",
  "lagatar thakan": "chronic fatigue",

  // === SLEEP DISTURBANCES ===
  "sleep disturbances": "sleep disturbances",
  "poor sleep": "sleep disturbances",
  "disturbed sleep": "sleep disturbances",
  "neend kharab": "sleep disturbances",

  // === DIGESTIVE ISSUES ===
  "digestive issues": "digestive issues",
  "digestion problems": "digestive issues",
  // "indigestion": "digestive issues",
  "hazma kharab": "digestive issues",

  // === URINARY TRACT INFECTION ===
  "uti": "urinary tract infection",
  "urinary tract infection": "urinary tract infection",
  "bladder infection": "urinary tract infection",
  "peshab ki infection": "urinary tract infection",

  // === KIDNEY STONES ===
  "kidney stones": "kidney stones",
  "renal colic": "kidney stones",
  "gurde ke pathri": "kidney stones",

  // === GALLSTONES ===
  "gallstones": "gallstones",
  "gall bladder stones": "gallstones",
  "pitte ke pathri": "gallstones",

  // === APPENDICITIS ===
  "appendicitis": "appendicitis",
  "appendix pain": "appendicitis",
  "pet mein dard right side": "appendicitis",

  // === CHOLECYSTITIS ===
  "cholecystitis": "cholecystitis",
  "gallbladder inflammation": "cholecystitis",
  "pitte mein infection": "cholecystitis",

  // === PEPTIC ULCER ===
  "peptic ulcer": "peptic ulcer",
  "stomach ulcer": "peptic ulcer",
  "pet ke ulcer": "peptic ulcer",

  // === ASTHMA ===
  "asthma": "asthma",
  "asthmatic": "asthma",
  // "breathing problem": "asthma",
  "dama": "asthma",

  // === BRONCHITIS ===
  "bronchitis": "bronchitis",
  "chest infection": "bronchitis",
  "lung infection": "bronchitis",

  // === PNEUMONIA ===
  "pneumonia": "pneumonia",
  // "lung infection": "pneumonia",
  "pneumonic": "pneumonia",

  // === TUBERCULOSIS ===
  "tuberculosis": "tuberculosis",
  "tb": "tuberculosis",
  "t.b.": "tuberculosis",
  "safed jwar": "tuberculosis",

  // === ANEMIA ===
  "anemia": "anemia",
  "anaemia": "anemia",
  "low hemoglobin": "anemia",
  "kam khoon": "anemia",

  // === DIABETES TYPES ===
  "type 1 diabetes": "diabetes",
  "type 2 diabetes": "diabetes",
  "diabetes mellitus": "diabetes",
  "sugar disease": "diabetes",

  // === HYPERTENSION ===
  // "high blood pressure": "hypertension",
  // "bp high": "hypertension",
  "elevated bp": "hypertension",

  // === HYPOTHYROIDISM ===
  "hypothyroidism": "hypothyroidism",
  "thyroid problem": "hypothyroidism",
  "thyroid low": "hypothyroidism",

  // === MIGRAINE ===
  // "migraine": "migraine",
  "migraine headache": "migraine",
  "severe headache": "migraine",

  // === SINUSITIS ===
  "sinusitis": "sinusitis",
  "sinus infection": "sinusitis",
  "sinus problem": "sinusitis",

  // === OTITIS MEDIA ===
  "otitis media": "otitis media",
  "ear infection": "otitis media",
  "middle ear infection": "otitis media",

  // === CONJUNCTIVITIS ===
  // "conjunctivitis": "conjunctivitis",
  "pink eye": "conjunctivitis",
  "eye infection": "conjunctivitis",

  // === URTICARIA ===
  "urticaria": "urticaria",
  "hives": "urticaria",
  "allergic reaction": "urticaria",

  // === CELLULITIS ===
  "cellulitis": "cellulitis",
  "skin infection": "cellulitis",
  "skin swelling": "cellulitis",

  // === ARTHRITIS ===
  // "arthritis": "arthritis",
  "joint inflammation": "arthritis",
  // "gathiya": "arthritis",

  // === OSTEOPOROSIS ===
  "osteoporosis": "osteoporosis",
  "bone weakness": "osteoporosis",
  "weak bones": "osteoporosis",

  // === GOUT ===
  "gout": "gout",
  "joint swelling": "gout",
  "gathi ka dard": "gout",

  // === FIBROMYALGIA ===
  "fibromyalgia": "fibromyalgia",
  "chronic pain": "fibromyalgia",
  "muscle tenderness": "fibromyalgia",

  // === IRRITABLE BOWEL SYNDROME ===
  "ibs": "irritable bowel syndrome",
  "irritable bowel syndrome": "irritable bowel syndrome",
  "bowel problem": "irritable bowel syndrome",

  // === CROHN'S DISEASE ===
  "crohn's disease": "crohn's disease",
  "inflammatory bowel disease": "crohn's disease",
  "ibd": "crohn's disease",

  // === ULCERATIVE COLITIS ===
  "ulcerative colitis": "ulcerative colitis",
  "colon inflammation": "ulcerative colitis",

  // === HEPATITIS ===
  "hepatitis": "hepatitis",
  "liver infection": "hepatitis",
  "jaundice": "hepatitis",

  // === CIRRHOSIS ===
  "cirrhosis": "cirrhosis",
  "liver cirrhosis": "cirrhosis",
  "liver damage": "cirrhosis",

  // === PANCREATITIS ===
  "pancreatitis": "pancreatitis",
  "pancreas inflammation": "pancreatitis",

  // === MEDICAL CONDITIONS ===
  // Common conditions and diseases
  // "common cold": "common cold",
  "influenza": "influenza",
  "flu": "influenza",
  "covid-19": "covid-19",
  "coronavirus": "covid-19",
  "gastroenteritis": "gastroenteritis",
  "food poisoning": "gastroenteritis",
  "tension headache": "tension headache",
  "cluster headache": "cluster headache",
  "sinus headache": "sinus headache",
  "iron deficiency anemia": "anemia",
  "pernicious anemia": "anemia",
  "allergic rhinitis": "allergic rhinitis",
  "hay fever": "allergic rhinitis",
  "tonsillitis": "tonsillitis",
  "pharyngitis": "pharyngitis",
  "laryngitis": "laryngitis",
  "bronchiectasis": "bronchiectasis",
  "copd": "copd",
  "chronic obstructive pulmonary disease": "copd",
  "emphysema": "emphysema",
  "pleural effusion": "pleural effusion",
  "pneumothorax": "pneumothorax",
  "hemothorax": "hemothorax",
  "pulmonary embolism": "pulmonary embolism",
  "deep vein thrombosis": "deep vein thrombosis",
  "dvt": "deep vein thrombosis",
  "myocardial infarction": "heart attack",
  "heart attack": "heart attack",
  "angina": "angina",
  // "arrhythmia": "arrhythmia",
  "atrial fibrillation": "atrial fibrillation",
  "afib": "atrial fibrillation",
  "congestive heart failure": "heart failure",
  "chf": "heart failure",
  "peripheral artery disease": "peripheral artery disease",
  "pad": "peripheral artery disease",
  "stroke": "stroke",
  "cerebral infarction": "stroke",
  "transient ischemic attack": "mini stroke",
  "tia": "mini stroke",
  "epilepsy": "epilepsy",
  "seizure": "seizure",
  "parkinson's disease": "parkinson's disease",
  "parkinson": "parkinson's disease",
  "multiple sclerosis": "multiple sclerosis",
  "ms": "multiple sclerosis",
  "alzheimer's disease": "alzheimer's disease",
  "dementia": "dementia",
  "osteoarthritis": "osteoarthritis",
  "rheumatoid arthritis": "rheumatoid arthritis",
  "ra": "rheumatoid arthritis",
  "systemic lupus erythematosus": "lupus",
  "sle": "lupus",
  "lupus": "lupus",
  "scleroderma": "scleroderma",
  "sjogren's syndrome": "sjogren's syndrome",
  "sjogren": "sjogren's syndrome",
  "ankylosing spondylitis": "ankylosing spondylitis",
  "psoriatic arthritis": "psoriatic arthritis",
  "gouty arthritis": "gout",
  "nephrotic syndrome": "nephrotic syndrome",
  "acute kidney injury": "acute kidney injury",
  "aki": "acute kidney injury",
  "chronic kidney disease": "chronic kidney disease",
  "ckd": "chronic kidney disease",
  "end stage renal disease": "end stage renal disease",
  "esrd": "end stage renal disease",
  "urinary incontinence": "urinary incontinence",
  "stress incontinence": "stress incontinence",
  "urge incontinence": "urge incontinence",
  "overflow incontinence": "overflow incontinence",
  "benign prostatic hyperplasia": "bph",
  "bph": "bph",
  "prostate enlargement": "bph",
  "interstitial cystitis": "interstitial cystitis",
  "bladder pain syndrome": "interstitial cystitis",
  "polycystic kidney disease": "polycystic kidney disease",
  "pkd": "polycystic kidney disease",
  "nephrolithiasis": "kidney stones",
  "urolithiasis": "kidney stones",
  "cholelithiasis": "gallstones",
  "choledocholithiasis": "gallstones",
  "acute pancreatitis": "pancreatitis",
  "chronic pancreatitis": "pancreatitis",
  "pancreatic insufficiency": "pancreatitis",
  "celiac disease": "celiac disease",
  "gluten intolerance": "celiac disease",
  // "inflammatory bowel disease": "inflammatory bowel disease",
  "diverticulitis": "diverticulitis",
  "diverticulosis": "diverticulosis",
  "hemorrhoids": "hemorrhoids",
  "piles": "hemorrhoids",
  "anal fissure": "anal fissure",
  "fistula": "fistula",
  "rectal prolapse": "rectal prolapse",
  "colorectal cancer": "colorectal cancer",
  "colon cancer": "colorectal cancer",
  "rectal cancer": "colorectal cancer",
  "esophageal cancer": "esophageal cancer",
  "stomach cancer": "stomach cancer",
  "pancreatic cancer": "pancreatic cancer",
  "liver cancer": "liver cancer",
  "hepatocellular carcinoma": "liver cancer",
  "gallbladder cancer": "gallbladder cancer",
  "breast cancer": "breast cancer",
  "lung cancer": "lung cancer",
  "prostate cancer": "prostate cancer",
  "bladder cancer": "bladder cancer",
  "kidney cancer": "kidney cancer",
  "ovarian cancer": "ovarian cancer",
  "cervical cancer": "cervical cancer",
  "endometrial cancer": "endometrial cancer",
  "thyroid cancer": "thyroid cancer",
  "melanoma": "melanoma",
  "basal cell carcinoma": "skin cancer",
  "squamous cell carcinoma": "skin cancer",
  "leukemia": "leukemia",
  "lymphoma": "lymphoma",
  "multiple myeloma": "multiple myeloma",
  "myeloma": "multiple myeloma",
  "acute myeloid leukemia": "leukemia",
  "aml": "leukemia",
  "acute lymphoblastic leukemia": "leukemia",
  "all": "leukemia",
  "chronic myeloid leukemia": "leukemia",
  "cml": "leukemia",
  "chronic lymphocytic leukemia": "leukemia",
  "cll": "leukemia",
  "hodgkin's lymphoma": "hodgkin's lymphoma",
  "non-hodgkin's lymphoma": "non-hodgkin's lymphoma",
  "thrombocytopenia": "thrombocytopenia",
  "thrombocytosis": "thrombocytosis",
  "neutropenia": "neutropenia",
  "leukopenia": "leukopenia",
  "leukocytosis": "leukocytosis",
  "eosinophilia": "eosinophilia",
  "monocytosis": "monocytosis",
  "lymphocytosis": "lymphocytosis",
  "aplastic anemia": "aplastic anemia",
  "thalassemia": "thalassemia",
  "sickle cell anemia": "sickle cell anemia",
  "hemophilia": "hemophilia",
  "von willebrand disease": "von willebrand disease",
  "idiopathic thrombocytopenic purpura": "itp",
  "itp": "itp",
  "disseminated intravascular coagulation": "dic",
  "dic": "dic",
  "thrombotic thrombocytopenic purpura": "ttp",
  "ttp": "ttp",
  "hemolytic uremic syndrome": "hus",
  "hus": "hus",
  "autoimmune hemolytic anemia": "autoimmune hemolytic anemia",
  "hypersplenism": "hypersplenism",
  "polycythemia vera": "polycythemia vera",
  "essential thrombocythemia": "essential thrombocythemia",
  "primary myelofibrosis": "primary myelofibrosis",
  "chronic myelomonocytic leukemia": "chronic myelomonocytic leukemia",
  "cmml": "chronic myelomonocytic leukemia",
  "myelodysplastic syndrome": "myelodysplastic syndrome",
  "mds": "myelodysplastic syndrome",
  "acute promyelocytic leukemia": "acute promyelocytic leukemia",
  "apl": "acute promyelocytic leukemia",
  "juvenile myelomonocytic leukemia": "juvenile myelomonocytic leukemia",
  "jmml": "juvenile myelomonocytic leukemia",
  "transient myeloproliferative disorder": "transient myeloproliferative disorder",
  "down syndrome associated leukemia": "down syndrome associated leukemia",
  "diamond-blackfan anemia": "diamond-blackfan anemia",
  "fanconi anemia": "fanconi anemia",
  "shwachman-diamond syndrome": "shwachman-diamond syndrome",
  "congenital dyserythropoietic anemia": "congenital dyserythropoietic anemia",
  "hereditary spherocytosis": "hereditary spherocytosis",
  "hereditary elliptocytosis": "hereditary elliptocytosis",
  "glucose-6-phosphate dehydrogenase deficiency": "g6pd deficiency",
  "g6pd deficiency": "g6pd deficiency",
  "pyruvate kinase deficiency": "pyruvate kinase deficiency",
  "congenital erythropoietic porphyria": "congenital erythropoietic porphyria",
  "erythropoietic protoporphyria": "erythropoietic protoporphyria",
  "acute intermittent porphyria": "acute intermittent porphyria",
  "variegate porphyria": "variegate porphyria",
  "hereditary coproporphyria": "hereditary coproporphyria",
  "porphyria cutanea tarda": "porphyria cutanea tarda",
  "hepatoerythropoietic porphyria": "hepatoerythropoietic porphyria",
  "x-linked protoporphyria": "x-linked protoporphyria",
  "alagille syndrome": "alagille syndrome",
  "alpha-1 antitrypsin deficiency": "alpha-1 antitrypsin deficiency",
  "cystic fibrosis": "cystic fibrosis",
  "cf": "cystic fibrosis",
  "primary ciliary dyskinesia": "primary ciliary dyskinesia",
  "kartagener syndrome": "kartagener syndrome",
  "surfactant protein deficiency": "surfactant protein deficiency",
  "neonatal respiratory distress syndrome": "neonatal respiratory distress syndrome",
  "nrds": "neonatal respiratory distress syndrome",
  "bronchopulmonary dysplasia": "bronchopulmonary dysplasia",
  "bpd": "bronchopulmonary dysplasia",
  "meconium aspiration syndrome": "meconium aspiration syndrome",
  "persistent pulmonary hypertension of the newborn": "persistent pulmonary hypertension of the newborn",
  "pphn": "persistent pulmonary hypertension of the newborn",
  "congenital diaphragmatic hernia": "congenital diaphragmatic hernia",
  "cdh": "congenital diaphragmatic hernia",
  "omphalocele": "omphalocele",
  "gastroschisis": "gastroschisis",
  "esophageal atresia": "esophageal atresia",
  "tracheoesophageal fistula": "tracheoesophageal fistula",
  "tef": "tracheoesophageal fistula",
  "duodenal atresia": "duodenal atresia",
  "jejunal atresia": "jejunal atresia",
  "ileal atresia": "ileal atresia",
  "meconium ileus": "meconium ileus",
  "necrotizing enterocolitis": "necrotizing enterocolitis",
  "nec": "necrotizing enterocolitis",
  "short bowel syndrome": "short bowel syndrome",
  "intestinal malrotation": "intestinal malrotation",
  "hirschsprung disease": "hirschsprung disease",
  "imperforate anus": "imperforate anus",
  "anorectal malformation": "anorectal malformation",
  "biliary atresia": "biliary atresia",
  "choledochal cyst": "choledochal cyst",
  "alcoholic liver disease": "alcoholic liver disease",
  "non-alcoholic fatty liver disease": "non-alcoholic fatty liver disease",
  "nafld": "non-alcoholic fatty liver disease",
  "non-alcoholic steatohepatitis": "non-alcoholic steatohepatitis",
  "nash": "non-alcoholic steatohepatitis",
  "primary biliary cirrhosis": "primary biliary cirrhosis",
  "pbc": "primary biliary cirrhosis",
  "primary sclerosing cholangitis": "primary sclerosing cholangitis",
  "psc": "primary sclerosing cholangitis",
  "autoimmune hepatitis": "autoimmune hepatitis",
  "aih": "autoimmune hepatitis",
  "wilson disease": "wilson disease",
  "hemochromatosis": "hemochromatosis",
  // "alpha-1 antitrypsin deficiency": "alpha-1 antitrypsin deficiency",
  "glycogen storage disease": "glycogen storage disease",
  "galactosemia": "galactosemia",
  "fructose intolerance": "fructose intolerance",
  "hereditary fructose intolerance": "hereditary fructose intolerance",
  "tyrosinemia": "tyrosinemia",
  "maple syrup urine disease": "maple syrup urine disease",
  "msud": "maple syrup urine disease",
  "phenylketonuria": "phenylketonuria",
  "pku": "phenylketonuria",
  "homocystinuria": "homocystinuria",
  "cystinuria": "cystinuria",
  "hartnup disease": "hartnup disease",
  "cystinosis": "cystinosis",
  "fanconi syndrome": "fanconi syndrome",
  "bartter syndrome": "bartter syndrome",
  "gitelman syndrome": "gitelman syndrome",
  "liddle syndrome": "liddle syndrome",
  "pseudohypoaldosteronism": "pseudohypoaldosteronism",
  "diabetes insipidus": "diabetes insipidus",
  "nephrogenic diabetes insipidus": "nephrogenic diabetes insipidus",
  "central diabetes insipidus": "central diabetes insipidus",
  "syndrome of inappropriate antidiuretic hormone": "siadh",
  "siadh": "siadh",
  "adrenal insufficiency": "adrenal insufficiency",
  "addison disease": "addison disease",
  "cushing syndrome": "cushing syndrome",
  "congenital adrenal hyperplasia": "congenital adrenal hyperplasia",
  "cah": "congenital adrenal hyperplasia",
  "pheochromocytoma": "pheochromocytoma",
  "neuroblastoma": "neuroblastoma",
  "retinoblastoma": "retinoblastoma",
  "wilms tumor": "wilms tumor",
  "hepatoblastoma": "hepatoblastoma",
  "medulloblastoma": "medulloblastoma",
  "ependymoma": "ependymoma",
  "pilocytic astrocytoma": "pilocytic astrocytoma",
  "glioblastoma": "glioblastoma",
  "gbm": "glioblastoma",
  "oligodendroglioma": "oligodendroglioma",
  "meningioma": "meningioma",
  "pituitary adenoma": "pituitary adenoma",
  "craniopharyngioma": "craniopharyngioma",
  "acoustic neuroma": "acoustic neuroma",
  "vestibular schwannoma": "acoustic neuroma",
  "meningocele": "meningocele",
  "myelomeningocele": "myelomeningocele",
  "encephalocele": "encephalocele",
  "hydrocephalus": "hydrocephalus",
  "dandy-walker syndrome": "dandy-walker syndrome",
  "chiari malformation": "chiari malformation",
  "syringomyelia": "syringomyelia",
  "tethered cord syndrome": "tethered cord syndrome",
  "spina bifida": "spina bifida",
  "anencephaly": "anencephaly",
  "holoprosencephaly": "holoprosencephaly",
  "agenesis of the corpus callosum": "agenesis of the corpus callosum",
  "lissencephaly": "lissencephaly",
  "polymicrogyria": "polymicrogyria",
  "schizencephaly": "schizencephaly",
  "porencephaly": "porencephaly",
  "arachnoid cyst": "arachnoid cyst",
  "pineal cyst": "pineal cyst",
  "colloid cyst": "colloid cyst",
  "epidermoid cyst": "epidermoid cyst",
  "dermoid cyst": "dermoid cyst",
  // "craniopharyngioma": "craniopharyngioma",
  // "pituitary adenoma": "pituitary adenoma",
  "prolactinoma": "prolactinoma",
  "cushing disease": "cushing disease",
  "acromegaly": "acromegaly",
  // "diabetes mellitus": "diabetes",
  "type 1 diabetes mellitus": "diabetes",
  "type 2 diabetes mellitus": "diabetes",
  "gestational diabetes": "gestational diabetes",
  "diabetic ketoacidosis": "diabetic ketoacidosis",
  "dka": "diabetic ketoacidosis",
  "hyperosmolar hyperglycemic state": "hyperosmolar hyperglycemic state",
  "hhs": "hyperosmolar hyperglycemic state",
  "diabetic neuropathy": "diabetic neuropathy",
  "diabetic retinopathy": "diabetic retinopathy",
  "diabetic nephropathy": "diabetic nephropathy",
  "diabetic foot": "diabetic foot",
  "hypoglycemia": "hypoglycemia",
  "insulin resistance": "insulin resistance",
  "metabolic syndrome": "metabolic syndrome",
  "polycystic ovary syndrome": "polycystic ovary syndrome",
  "pcos": "polycystic ovary syndrome",
  "endometriosis": "endometriosis",
  "adenomyosis": "adenomyosis",
  "uterine fibroids": "uterine fibroids",
  "leiomyoma": "uterine fibroids",
  "ovarian cyst": "ovarian cyst",
  "endometrial hyperplasia": "endometrial hyperplasia",
  "premature ovarian failure": "premature ovarian failure",
  "premature menopause": "premature menopause",
  "menopause": "menopause",
  "perimenopause": "perimenopause",
  "postmenopause": "postmenopause",
  // "dysmenorrhea": "dysmenorrhea",
  "amenorrhea": "amenorrhea",
  "oligomenorrhea": "oligomenorrhea",
  "polymenorrhea": "polymenorrhea",
  "menorrhagia": "menorrhagia",
  "metrorrhagia": "metrorrhagia",
  "postmenopausal bleeding": "postmenopausal bleeding",
  "pelvic inflammatory disease": "pelvic inflammatory disease",
  "pid": "pelvic inflammatory disease",
  // "endometriosis": "endometriosis",
  // "adenomyosis": "adenomyosis",
  "uterine prolapse": "uterine prolapse",
  "cervical insufficiency": "cervical insufficiency",
  "incompetent cervix": "cervical insufficiency",
  "placenta previa": "placenta previa",
  "placental abruption": "placental abruption",
  "preeclampsia": "preeclampsia",
  "eclampsia": "eclampsia",
  "gestational hypertension": "gestational hypertension",
  // "gestational diabetes": "gestational diabetes",
  "hyperemesis gravidarum": "hyperemesis gravidarum",
  "ectopic pregnancy": "ectopic pregnancy",
  "molar pregnancy": "molar pregnancy",
  "miscarriage": "miscarriage",
  "spontaneous abortion": "miscarriage",
  "stillbirth": "stillbirth",
  "intrauterine growth restriction": "intrauterine growth restriction",
  "iugr": "intrauterine growth restriction",
  "preterm labor": "preterm labor",
  "preterm birth": "preterm birth",
  "postpartum hemorrhage": "postpartum hemorrhage",
  "retained placenta": "retained placenta",
  "puerperal infection": "puerperal infection",
  "mastitis": "mastitis",
  "breast engorgement": "breast engorgement",
  "postpartum depression": "postpartum depression",
  "postpartum thyroiditis": "postpartum thyroiditis",
  "sheehan syndrome": "sheehan syndrome",
  "peripartum cardiomyopathy": "peripartum cardiomyopathy",
  "amniotic fluid embolism": "amniotic fluid embolism",
  "venous thromboembolism": "venous thromboembolism",
  "vte": "venous thromboembolism",
  "deep venous thrombosis": "deep vein thrombosis",
  // "pulmonary embolism": "pulmonary embolism",
  "cerebral venous thrombosis": "cerebral venous thrombosis",
  "ovarian vein thrombosis": "ovarian vein thrombosis",
  // "breast cancer": "breast cancer",
  // "cervical cancer": "cervical cancer",
  // "ovarian cancer": "ovarian cancer",
  // "endometrial cancer": "endometrial cancer",
  "vulvar cancer": "vulvar cancer",
  "vaginal cancer": "vaginal cancer",
  "gestational trophoblastic disease": "gestational trophoblastic disease",
  "choriocarcinoma": "choriocarcinoma",
  "fibroadenoma": "fibroadenoma",
  "breast cyst": "breast cyst",
  "intraductal papilloma": "intraductal papilloma",
  "phyllodes tumor": "phyllodes tumor",
  "ductal carcinoma in situ": "dcis",
  "dcis": "dcis",
  "invasive ductal carcinoma": "invasive ductal carcinoma",
  "invasive lobular carcinoma": "invasive lobular carcinoma",
  "triple negative breast cancer": "triple negative breast cancer",
  "her2 positive breast cancer": "her2 positive breast cancer",
  "hormone receptor positive breast cancer": "hormone receptor positive breast cancer",
  // "prostate cancer": "prostate cancer",
  // "benign prostatic hyperplasia": "bph",
  "prostatitis": "prostatitis",
  "epididymitis": "epididymitis",
  "orchitis": "orchitis",
  "testicular torsion": "testicular torsion",
  "varicocele": "varicocele",
  "hydrocele": "hydrocele",
  "spermatocoele": "spermatocoele",
  "inguinal hernia": "inguinal hernia",
  "femoral hernia": "femoral hernia",
  "umbilical hernia": "umbilical hernia",
  "incisional hernia": "incisional hernia",
  "hiatal hernia": "hiatal hernia",
  "diaphragmatic hernia": "diaphragmatic hernia",
  "sports hernia": "sports hernia",
  "obesity": "obesity",
  "overweight": "overweight",
  "underweight": "underweight",
  "eating disorder": "eating disorder",
  "anorexia nervosa": "anorexia nervosa",
  "bulimia nervosa": "bulimia nervosa",
  "binge eating disorder": "binge eating disorder",
  "pica": "pica",
  "rumination disorder": "rumination disorder",
  "avoidant restrictive food intake disorder": "arfid",
  "arfid": "arfid",
  "cachexia": "cachexia",
  "sarcopenia": "sarcopenia",
  "osteomalacia": "osteomalacia",
  "rickets": "rickets",
  "vitamin d deficiency": "vitamin d deficiency",
  "calcium deficiency": "calcium deficiency",
  "iron deficiency": "iron deficiency",
  "vitamin b12 deficiency": "vitamin b12 deficiency",
  "folate deficiency": "folate deficiency",
  "zinc deficiency": "zinc deficiency",
  "copper deficiency": "copper deficiency",
  "selenium deficiency": "selenium deficiency",
  "iodine deficiency": "iodine deficiency",
  "magnesium deficiency": "magnesium deficiency",
  "potassium deficiency": "potassium deficiency",
  "sodium excess": "sodium excess",
  "hypernatremia": "hypernatremia",
  "hyponatremia": "hyponatremia",
  "hyperkalemia": "hyperkalemia",
  "hypokalemia": "hypokalemia",
  "hypercalcemia": "hypercalcemia",
  "hypocalcemia": "hypocalcemia",
  "hypermagnesemia": "hypermagnesemia",
  "hypomagnesemia": "hypomagnesemia",
  "metabolic acidosis": "metabolic acidosis",
  "metabolic alkalosis": "metabolic alkalosis",
  "respiratory acidosis": "respiratory acidosis",
  "respiratory alkalosis": "respiratory alkalosis",
  "lactic acidosis": "lactic acidosis",
  // "diabetic ketoacidosis": "diabetic ketoacidosis",
  "starvation ketoacidosis": "starvation ketoacidosis",
  "alcoholic ketoacidosis": "alcoholic ketoacidosis",
  "acid-base imbalance": "acid-base imbalance",
  "fluid overload": "fluid overload",
  "hypervolemia": "hypervolemia",
  "dehydration": "dehydration",
  "hypovolemia": "hypovolemia",
  "shock": "shock",
  "hypovolemic shock": "hypovolemic shock",
  "cardiogenic shock": "cardiogenic shock",
  "distributive shock": "distributive shock",
  "septic shock": "septic shock",
  "anaphylactic shock": "anaphylactic shock",
  "neurogenic shock": "neurogenic shock",
  "obstructive shock": "obstructive shock",
  "multiple organ dysfunction syndrome": "multiple organ dysfunction syndrome",
  "mods": "multiple organ dysfunction syndrome",
  "systemic inflammatory response syndrome": "systemic inflammatory response syndrome",
  "sirs": "systemic inflammatory response syndrome",
  "sepsis": "sepsis",
  "severe sepsis": "severe sepsis",
  "septicemia": "septicemia",
  "bacteremia": "bacteremia",
  "fungemia": "fungemia",
  "viremia": "viremia",
  "parasitemia": "parasitemia",
  "toxemia": "toxemia",
  "endotoxemia": "endotoxemia",
  "fever": "fever" // Keep as fever for intent detection
};
