 // spellCorrector.ts
const STOP_WORDS = new Set([
  "mujhe", "mujh", "hai", "ha", "ho",
  "chahiye", "batao", "dikhao",
  "problem", "issue",
  "male", "female", "man", "woman",
  "me", "my", "i", "you",
  "skin", "heart", "bone", "eye",
  "have", "has", "had", "having"
]);

const TYPO_MAP: Record<string, string> = {
  // GENDER typos (including normalization)
  "m": "male",
  "ma": "male",
  "mal": "male",
  "maale": "male",
  "mael": "male",
  "mle": "male",
  "ladka": "male",
  "boy": "male",

  "f": "female",
  "fe": "female",
  "fem": "female",
  "femal": "female",
  "femail": "female",
  "femle": "female",
  "ladki": "female",
  "girl": "female",

  "trans": "trans",
  "transgender": "trans",

  // AGE typos
  "agee": "age",
  "aeg": "age",
  "ag": "age",
  "dge": "age",
  "agw": "age",
  "aj": "age",
  "ae": "age",
  "hav": "age",
  "hve": "age",
  "hae": "age",

  // GENDER typos (additional)
  "gnder": "gender",
  "gende": "gender",
  "gnr": "gender",
  "gendre": "gender",
  "gen": "gender",
  "gdar": "gender",
  "gnd": "gender",
  "gndr": "gender",
  "ganr": "gender",
  "genderr": "gender",

  // HEIGHT typos
  "hieght": "height",
  "heigt": "height",
  "hght": "height",
  "hgt": "height",
  "ht": "height",
  "heit": "height",
  "heght": "height",
  "heiht": "height",
  "hiegh": "height",
  "heigth": "height",

  // WEIGHT typos
  "wight": "weight",
  "wieght": "weight",
  "wegit": "weight",
  "wgt": "weight",
  "whigt": "weight",
  "weit": "weight",
  "weig": "weight",
  "w8": "weight",
  "wt": "weight",

  // BLOOD GROUP typos
  "bloodgroup": "blood_group",
  "bld grp": "blood_group",
  "blod grp": "blood_group",
  "bldgroup": "blood_group",
  "bldgrp": "blood_group",
  "bloodgrp": "blood_group",
  "blood groop": "blood_group",
  "bloodgruop": "blood_group",
  "bg": "blood_group",

  // ADDRESS typos
  "adress": "address",
  "addres": "address",
  "adres": "address",
  "address": "address",
  "adrress": "address",
  "adr": "address",
  "addrs": "address",
  "addresz": "address",
  "adala": "address",
  "add": "address",

  // LOCATION typos
  "loc": "location",
  "loaction": "location",
  "loction": "location",
  "loacation": "location",
  "lacation": "location",
  "lctn": "location",
  "lcoation": "location",
  "loac": "location",
  "locn": "location",
};

const KNOWN_WORDS = [
  // profile fields
  "age", "gender", "height", "weight",

  // specialists (DB-aligned)
  "dermatologist",
  "cardiologist",
  "orthopedic",
  "ophthalmologist",
  "general physician",

  // medical conditions
  "diabetes",
  "hypertension",
  "fever",
  "pain",
  "acne",
  "headache",
  "cough",
  "nausea",
  "vomiting",
  "dizziness",
  "fatigue",
  "rash",
  "itching",
  "swelling",
  "bruising",
  "bleeding",
  "infection",
  "inflammation",
  "arthritis",
  "asthma",
  "bronchitis",
  "pneumonia",
  "migraine",
  "depression",
  "anxiety",
  "insomnia",
  "diarrhea",
  "constipation",
  "abdominal pain",
  "chest pain",
  "back pain",
  "joint pain",
  "muscle pain",
  "sore throat",
  "ear pain",
  "toothache",
  "sinusitis",
  "allergy",
  "eczema",
  "psoriasis",
  "dermatitis",
  "ulcer",
  "burn",
  "fracture",
  "sprain",
  "strain",
  "concussion",
  "stroke",
  "heart attack",
  "hypertension",
  "hypotension",
  "anemia",
  "jaundice",
  "hepatitis",
  "cirrhosis",
  "kidney stones",
  "uti",
  "urinary tract infection",
  "menstrual cramps",
  "pcos",
  "endometriosis",
  "fibroids",
  "prostate enlargement",
  "erectile dysfunction",
  "infertility",
  "pregnancy",
  "miscarriage",
  "abortion",
  "labor",
  "delivery",
  "postpartum",
  "breastfeeding",
  "colic",
  "teething",
  "measles",
  "chickenpox",
  "mumps",
  "rubella",
  "whooping cough",
  "diphtheria",
  "tetanus",
  "polio",
  "hepatitis",
  "tuberculosis",
  "malaria",
  "dengue",
  "chikungunya",
  "zika",
  "ebola",
  "covid",
  "flu",
  "cold",
  "sars",
  "mers",
  "hiv",
  "aids",
  "syphilis",
  "gonorrhea",
  "chlamydia",
  "herpes",
  "hpv",
  "warts",
  "cancer",
  "tumor",
  "cyst",
  "abscess",
  "gangrene",
  "sepsis",
  "shock",
  "coma",
  "epilepsy",
  "parkinsons",
  "alzheimers",
  "dementia",
  "multiple sclerosis",
  "als",
  "huntingtons",
  "cerebral palsy",
  "down syndrome",
  "autism",
  "adhd",
  "dyslexia",
  "bipolar",
  "schizophrenia",
  "ptsd",
  "ocd",
  "phobia",
  "eating disorder",
  "anorexia",
  "bulimia",
  "obesity",
  "diabetes mellitus",
  "hypothyroidism",
  "hyperthyroidism",
  "addisons",
  "cushings",
  "acromegaly",
  "gigantism",
  "dwarfism",
  "osteoporosis",
  "rheumatoid arthritis",
  "lupus",
  "scleroderma",
  "sjogrens",
  "vasculitis",
  "gout",
  "podagra",
  "bursitis",
  "tendinitis",
  "carpal tunnel",
  "sciatica",
  "herniated disc",
  "spinal stenosis",
  "ankylosing spondylitis",
  "fibromyalgia",
  "chronic fatigue syndrome",
  "lyme disease",
  "west nile",
  "zoster",
  "shingles",
  "mononucleosis",
  "glandular fever",
  "roseola",
  "hand foot mouth",
  "scarlet fever",
  "strep throat",
  "tonsillitis",
  "laryngitis",
  "pharyngitis",
  "tracheitis",
  "bronchiolitis",
  "croup",
  "pertussis",
  "rsv",
  "respiratory syncytial virus",
  "hmpv",
  "human metapneumovirus",
  "adenovirus",
  "rhinovirus",
  "coronavirus",
  "parainfluenza",
  "mycoplasma",
  "chlamydophila",
  "legionella",
  "histoplasma",
  "coccidioides",
  "blastomyces",
  "cryptococcus",
  "aspergillus",
  "candida",
  "staphylococcus",
  "streptococcus",
  "escherichia coli",
  "salmonella",
  "shigella",
  "campylobacter",
  "vibrio",
  "yersinia",
  "clostridium",
  "bacillus",
  "corynebacterium",
  "mycobacterium",
  "nocardia",
  "actinomyces",
  "fusobacterium",
  "peptostreptococcus",
  "bacteroides",
  "prevotella",
  "porphyromonas",
  "fusobacterium",
  "veillonella",
  "leptotrichia",
  "capnocytophaga",
  "eikenella",
  "kingella",
  "neisseria",
  "moraxella",
  "haemophilus",
  "bordetella",
  "francisella",
  "brucella",
  "pasteurella",
  "erysipelothrix",
  "listeria",
  "erwinia",
  "serratia",
  "proteus",
  "providencia",
  "morganella",
  "klebsiella",
  "enterobacter",
  "citrobacter",
  "serratia",
  "hafnia",
  "edwardsiella",
  "pantoea",
  "raoultella",
  "cronobacter",
  "saccharomyces",
  "cryptococcus",
  "pneumocystis",
  "toxoplasma",
  "plasmodium",
  "babesia",
  "leishmania",
  "trypanosoma",
  "schistosoma",
  "fasciola",
  "opisthorchis",
  "clonorchis",
  "paragonimus",
  "echinococcus",
  "taenia",
  "hymenolepis",
  "dipylidium",
  "spirometra",
  "diphyllobothrium",
  "anisakis",
  "gnathostoma",
  "angiostrongylus",
  "toxocara",
  "ascaris",
  "trichuris",
  "enterobius",
  "strongyloides",
  "hookworm",
  "necator",
  "ancylostoma",
  "trichostrongylus",
  "ostertagia",
  "haemonchus",
  "dictyocaulus",
  "metastrongylus",
  "muellerius",
  "protostrongylus",
  "elaphostrongylus",
  "parelaphostrongylus",
  "angiostrongylus",
  "crenosoma",
  "filaroides",
  "oslerus",
  "stewardsonia",
  "capillaria",
  "eucoleus",
  "trichinella",
  "dracunculus",
  "wuchereria",
  "brugia",
  "mansonella",
  "loa",
  "onchocerca",
  "dirofilaria",
  "dipetalonema",
  "acanthocheilonema",
  "setaria",
  "stephanofilaria",
  "habronema",
  "draschia",
  "spirocerca",
  "thelazia",
  "gnat",
  "blackfly",
  "tsetse",
  "kissing bug",
  "louse",
  "flea",
  "tick",
  "mite",
  "scabies",
  "pediculosis",
  "myiasis",
  "cutaneous larva migrans",
  "visceral larva migrans",
  "ocular larva migrans",
  "toxocariasis",
  "ascariasis",
  "trichuriasis",
  "enterobiasis",
  "strongyloidiasis",
  "hookworm infection",
  "trichostrongyliasis",
  "capillariasis",
  "trichinosis",
  "dracunculiasis",
  "filariasis",
  "loiasis",
  "onchocerciasis",
  "dirofilariasis",
  "setariasis",
  "stephanofilaria",
  "habronemiasis",
  "draschia",
  "spirocercosis",
  "thelaziasis",
  "gnathostomiasis",
  "angiostrongyliasis",
  "paragonimiasis",
  "echinococcosis",
  "taeniasis",
  "hymenolepiasis",
  "dipylidiasis",
  "spirometrosis",
  "diphyllobothriasis",
  "anisakiasis",
  "cysticercosis",
  "alveolar echinococcosis",
  "neurocysticercosis",
  "hydatid disease",
  "fascioliasis",
  "opisthorchiasis",
  "clonorchiasis",
  "schistosomiasis",
  "intestinal schistosomiasis",
  "urinary schistosomiasis",
  "hepatic schistosomiasis",
  "pulmonary schistosomiasis",
  "cerebral schistosomiasis",
  "cutaneous schistosomiasis",
  "leishmaniasis",
  "visceral leishmaniasis",
  "cutaneous leishmaniasis",
  "mucocutaneous leishmaniasis",
  "chagas disease",
  "trypanosomiasis",
  "african trypanosomiasis",
  "american trypanosomiasis",
  "babesiosis",
  "malaria",
  "toxoplasmosis",
  "cryptosporidiosis",
  "giardiasis",
  "isosporiasis",
  "cyclosporiasis",
  "microsporidiosis",
  "balantidiasis",
  "amebiasis",
  "trichomoniasis",
  "giardiasis",
  "cryptosporidiosis",
  "isosporiasis",
  "cyclosporiasis",
  "microsporidiosis",
  "balantidiasis",
  "amebiasis",
  "trichomoniasis",
  "leptospirosis",
  "brucellosis",
  "tularemia",
  "plague",
  "melioidosis",
  "glanders",
  "anthrax",
  "botulism",
  "tetanus",
  "diphtheria",
  "pertussis",
  "scarlet fever",
  "erysipelas",
  "impetigo",
  "cellulitis",
  "necrotizing fasciitis",
  "gas gangrene",
  "actinomycosis",
  "nocardiosis",
  "mycetoma",
  "chromoblastomycosis",
  "lobomycosis",
  "paracoccidioidomycosis",
  "histoplasmosis",
  "blastomycosis",
  "coccidioidomycosis",
  "sporotrichosis",
  "aspergillosis",
  "zygomycosis",
  "mucormycosis",
  "candidiasis",
  "cryptococcosis",
  "pneumocystosis",
  "malassezia",
  "dermatophytosis",
  "pityriasis versicolor",
  "tinea",
  "onychomycosis",
  "kerion",
  "favus",
  "white piedra",
  "black piedra",
  "trichosporonosis",
  "alternariosis",
  "curvularia",
  "exserohilum",
  "fonsecaea",
  "phialophora",
  "ramichloridium",
  "scytalidium",
  "verticillium",
  "xanthomonas",
  "burkholderia",
  "pseudomonas",
  "acinetobacter",
  "stenotrophomonas",
  "aeromonas",
  "pleisiomonas",
  "plesiomonas",
  "vibrio",
  "photobacterium",
  "listonella",
  "moritella",
  "shewanella",
  "colwellia",
  "psychrobacter",
  "moraxella",
  "acinetobacter",
  "oligella"]
  

function editDistance(a: string, b: string): number {
  const dp = Array.from({ length: a.length + 1 }, () =>
    Array(b.length + 1).fill(0)
  );

  for (let i = 0; i <= a.length; i++) dp[i][0] = i;
  for (let j = 0; j <= b.length; j++) dp[0][j] = j;

  for (let i = 1; i <= a.length; i++) {
    for (let j = 1; j <= b.length; j++) {
      dp[i][j] = Math.min(
        dp[i - 1][j] + 1,
        dp[i][j - 1] + 1,
        dp[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1)
      );
    }
  }

  return dp[a.length][b.length];
}

export function correctSpelling(token: string): string | null {
  // Check stop words first
  if (STOP_WORDS.has(token)) return null;

  // Check direct typo map first (even for short tokens)
  const directCorrection = TYPO_MAP[token.toLowerCase()];
  if (directCorrection) return directCorrection;

  // Skip edit distance for tokens <= 3 characters
  if (token.length <= 3) return null;

  // Fallback to edit distance on known words
  let bestMatch: string | null = null;
  let minDistance = Infinity;

  for (const word of KNOWN_WORDS) {
    const dist = editDistance(token, word);
    if (dist < minDistance && dist <= 2) {
      minDistance = dist;
      bestMatch = word;
    }
  }

  return bestMatch;
}
