// states.ts

export enum ConversationState {
  IDLE = "IDLE",
  HANDLE_INTENT = "HANDLE_INTENT",
 UPDATE_PROFILE_FIELD = "UPDATE_PROFILE_FIELD",
  ASK_WHICH_PROFILE_FIELD = "ASK_WHICH_PROFILE_FIELD",
  ASK_NEW_FIELD_VALUE = "ASK_NEW_FIELD_VALUE",
  ASK_SYMPTOMS = "ASK_SYMPTOMS",
CONFIRM_PROFILE = "CONFIRM_PROFILE",
  
  ASK_AGE = "ASK_AGE",
  ASK_GENDER = "ASK_GENDER",
  ASK_HEIGHT = "ASK_HEIGHT",
  ASK_WEIGHT = "ASK_WEIGHT",
  ASK_LOCATION = "ASK_LOCATION",

  MEDICAL_CONTEXT_ANALYSIS = "MEDICAL_CONTEXT_ANALYSIS",
  DISEASE_RISK_EVALUATION = "DISEASE_RISK_EVALUATION",
  SPECIALIST_RECOMMENDATION = "SPECIALIST_RECOMMENDATION",

  CONFIRM_BOOKING = "CONFIRM_BOOKING",
  BOOK_APPOINTMENT = "BOOK_APPOINTMENT",

  EMERGENCY_FLOW = "EMERGENCY_FLOW",
  END = "END"
}
