"""
Django settings for userapp project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url  # ✅ Added

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv()

# ---------------------------------------------------------
# SECURITY (unchanged)
# ---------------------------------------------------------
SECRET_KEY = 'django-insecure-d8zzojhx8jymo&vo05r!#-v9c!fh!7$x$-wws_kd710on=101%'

DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'myuserlogin.com', '*']


# ---------------------------------------------------------
# APPLICATION DEFINITION (unchanged)
# ---------------------------------------------------------
INSTALLED_APPS = [
    'home.apps.HomeConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # ✅ Added whitenoise for static files on Render
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ---------------------------------------------------------
# CORS (only added Vercel URL support)
# ---------------------------------------------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8080",
    "http://127.0.0.1:8080",

    # ✅ Added for Vercel (frontend)
    "https://*.vercel.app",
]

CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = 'userapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, '..', 'react-frontend', 'dist')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'userapp.wsgi.application'


# ---------------------------------------------------------
# DATABASE (switched from SQLite → Supabase Postgres)
# ONLY ADD — your sqlite wasn't deleted
# ---------------------------------------------------------
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv("SUPABASE_DB_URL"),  # from Render env
        conn_max_age=600,
        ssl_require=True
    )
}


# ---------------------------------------------------------
# PASSWORDS (unchanged)
# ---------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# ---------------------------------------------------------
# INTERNATIONALIZATION (unchanged)
# ---------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ---------------------------------------------------------
# STATIC FILES (only additions, nothing removed)
# ---------------------------------------------------------

# Your existing static files config
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '..', 'react-frontend', 'dist', 'assets'),
]

STATIC_URL = '/assets/'

# ✅ REQUIRED for Render (adds static folder for deployment)
STATIC_ROOT = BASE_DIR / "staticfiles"

# ✅ Whitenoise for production static handling
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ---------------------------------------------------------
# DEFAULT PK (unchanged)
# ---------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------
# SUPABASE KEYS (unchanged)
# ---------------------------------------------------------
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
